/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new exam or practice session */
        post: operations["startExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{examId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish exam and get results */
        post: operations["finishExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{examId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer for a question (in practice mode, returns explanation) */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/critical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCritical"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/chapter/{chapter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getByChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get exam session details */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{examId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get exam result (must be completed) */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top scores leaderboard */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get exam history for current user */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StartExamRequest: {
            examType: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            durationMinutes?: number;
            mode?: string;
        };
        ApiResponseExamSessionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamSessionResponse"];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ExamSessionResponse: {
            /** Format: uuid */
            examId?: string;
            examType?: string;
            status?: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            answeredCount?: number;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: date-time */
            expiresAt?: string;
            mode?: string;
            questions?: components["schemas"]["QuestionResponse"][];
            /** Format: date-time */
            startedAt?: string;
        };
        QuestionResponse: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            chapter?: number;
            questionText?: string;
            options?: Record<string, never>;
            isCritical?: boolean;
            imageUrl?: string;
        };
        ApiResponseExamResultResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamResultResponse"];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ExamResultResponse: {
            /** Format: uuid */
            examId?: string;
            examType?: string;
            status?: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            correctCount?: number;
            /** Format: int32 */
            wrongCount?: number;
            /** Format: int32 */
            score?: number;
            passed?: boolean;
            mode?: string;
            /** Format: int32 */
            durationMinutes?: number;
            answers?: {
                [key: string]: Record<string, never>;
            }[];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        SubmitAnswerRequest: {
            questionId: string;
            selectedAnswer: string;
        };
        ApiResponseSubmitAnswerResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SubmitAnswerResponse"];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        SubmitAnswerResponse: {
            status?: string;
            isCorrect?: boolean;
            correctAnswer?: string;
            explanation?: string;
        };
        ApiResponseQuestionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionResponse"];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ApiResponseMapStringObject: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: Record<string, never>;
            };
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ApiResponseListQuestionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionResponse"][];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ApiResponseListLeaderboardEntry: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaderboardEntry"][];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        LeaderboardEntry: {
            /** Format: uuid */
            userId?: string;
            examType?: string;
            /** Format: int32 */
            score?: number;
            /** Format: int32 */
            correctCount?: number;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: date-time */
            completedAt?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageExamHistoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageExamHistoryResponse"];
            /** Format: date-time */
            timestamp?: string;
            traceId?: string;
        };
        ExamHistoryResponse: {
            /** Format: uuid */
            examId?: string;
            examType?: string;
            status?: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            correctCount?: number;
            /** Format: int32 */
            wrongCount?: number;
            /** Format: int32 */
            score?: number;
            passed?: boolean;
            mode?: string;
            /** Format: int32 */
            durationMinutes?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        PageExamHistoryResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            numberOfElements?: number;
            content?: components["schemas"]["ExamHistoryResponse"][];
            sort?: components["schemas"]["SortObject"][];
            first?: boolean;
            last?: boolean;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            unpaged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"][];
        };
        SortObject: {
            direction?: string;
            nullHandling?: string;
            ascending?: boolean;
            property?: string;
            ignoreCase?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamSessionResponse"];
                };
            };
        };
    };
    finishExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResultResponse"];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSubmitAnswerResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    getCritical: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionResponse"];
                };
            };
        };
    };
    getByChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamSessionResponse"];
                };
            };
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamResultResponse"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                examType?: string;
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLeaderboardEntry"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageExamHistoryResponse"];
                };
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
}
