/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/progress/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a study or exam session */
        post: operations["logSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get progress for all chapters */
        get: operations["getChapterProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update progress for a chapter (record answers) */
        patch: operations["updateChapterProgress"];
        trace?: never;
    };
    "/api/v1/progress/streaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get study streak information */
        get: operations["getStreak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent study sessions */
        get: operations["getRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get study session history (paginated) */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's learning dashboard with overall statistics */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LogStudySessionRequest: {
            sessionType: string;
            examType?: string;
            mode?: string;
            /** Format: uuid */
            examId?: string;
            /** Format: int32 */
            questionsCount: number;
            /** Format: int32 */
            correctCount: number;
            /** Format: int32 */
            wrongCount: number;
            /** Format: int32 */
            durationSeconds: number;
        };
        ApiResponseSessionHistoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SessionHistoryResponse"];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        SessionHistoryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            examId?: string;
            sessionType?: string;
            examType?: string;
            mode?: string;
            status?: string;
            /** Format: int32 */
            questionsCount?: number;
            /** Format: int32 */
            correctCount?: number;
            /** Format: int32 */
            wrongCount?: number;
            /** Format: double */
            score?: number;
            passed?: boolean;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        UpdateChapterProgressRequest: {
            /** Format: int32 */
            chapterId: number;
            chapterName: string;
            /** Format: int32 */
            questionsTotal: number;
            /** Format: int32 */
            questionsCount: number;
            /** Format: int32 */
            correctCount: number;
            /** Format: int32 */
            wrongCount?: number;
        };
        ApiResponseChapterProgressResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ChapterProgressResponse"];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ChapterProgressResponse: {
            /** Format: int32 */
            chapterId?: number;
            chapterName?: string;
            status?: string;
            /** Format: int32 */
            questionsAnswered?: number;
            /** Format: int32 */
            questionsTotal?: number;
            /** Format: int32 */
            correctCount?: number;
            /** Format: double */
            score?: number;
            /** Format: double */
            completionPercent?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            lastStudiedAt?: string;
        };
        ApiResponseStreakResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StreakResponse"];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        StreakResponse: {
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            longestStreak?: number;
            /** Format: date */
            lastStudyDate?: string;
            studiedToday?: boolean;
        };
        ApiResponseListSessionHistoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SessionHistoryResponse"][];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageSessionHistoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageSessionHistoryResponse"];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PageSessionHistoryResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            numberOfElements?: number;
            content?: components["schemas"]["SessionHistoryResponse"][];
            sort?: components["schemas"]["SortObject"][];
            first?: boolean;
            last?: boolean;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            unpaged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"][];
        };
        SortObject: {
            direction?: string;
            nullHandling?: string;
            ascending?: boolean;
            property?: string;
            ignoreCase?: boolean;
        };
        ApiResponseDashboardResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DashboardResponse"];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DashboardResponse: {
            /** Format: int32 */
            totalExams?: number;
            /** Format: int32 */
            totalPracticeSessions?: number;
            /** Format: int64 */
            totalStudyTimeSeconds?: number;
            /** Format: int32 */
            totalQuestionsAnswered?: number;
            /** Format: int32 */
            totalCorrectAnswers?: number;
            /** Format: double */
            averageScore?: number;
            /** Format: int32 */
            examsPassed?: number;
            /** Format: int32 */
            examsFailed?: number;
            /** Format: double */
            passRate?: number;
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            longestStreak?: number;
            /** Format: date */
            lastStudyDate?: string;
            /** Format: int32 */
            chaptersTotal?: number;
            /** Format: int32 */
            chaptersCompleted?: number;
            /** Format: int32 */
            chaptersInProgress?: number;
            /** Format: double */
            chaptersProgressPercent?: number;
        };
        ApiResponseListChapterProgressResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ChapterProgressResponse"][];
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseMapStringString: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: string;
            };
            errorCode?: string;
            traceId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogStudySessionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSessionHistoryResponse"];
                };
            };
        };
    };
    getChapterProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListChapterProgressResponse"];
                };
            };
        };
    };
    updateChapterProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChapterProgressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseChapterProgressResponse"];
                };
            };
        };
    };
    getStreak: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStreakResponse"];
                };
            };
        };
    };
    getRecent: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSessionHistoryResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageSessionHistoryResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponse"];
                };
            };
        };
    };
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringString"];
                };
            };
        };
    };
}
